name: PY Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your main branch name
      
permissions:
  contents: read
  
env:
  shards : ${{ secrets.SHARDS }}
  token : ${{ secrets.TOKEN }}
  prefix : ${{ secrets.PREFIX }}
  spot_id : ${{ secrets.SPOT_ID }}
  spot_secret : ${{ secrets.SPOT_SECRET }}
  
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9  # Change this to your desired Python version

    - name: Install dependencies
      run: |
        pip install -r dep.txt
      working-directory: ./  # Change this to your project's root directory

    - name: Deploy
      run: |
        # Add any deployment commands here
        # For example, to run your Python application:
        python main.py
