name: Deployment

on:
  schedule:
    - cron: '0 */5 * * *'  # This cron expression means "Every 5 hours"
  workflow_dispatch:
  push:
    branches:
      - main
    
permissions:
  contents: read
  
env:
  # mongo_url  : ${{ secrets.MONGO_URL }}
  shards : ${{ secrets.SHARDS }}
  token : ${{ secrets.TOKEN }}
  prefix : ${{ secrets.PREFIX }}
  spot_id : ${{ secrets.SPOT_ID }}
  spot_secret : ${{ secrets.SPOT_SECRET }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dep.txt
        # sudo apt-get update && sudo apt-get install -y default-jdk
      working-directory: ./
        
    # - name: Install ffmpeg
    #   run: 
    #     sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Deployment
      run: |
        python main.py 
 
